const imageMap = {
  supporter: 'Supporter.png',
  doctor: 'doctor.png',
  mattress_evaluator : 'mattress evaluator.png',
  real_estate_agent : 'real estate agent.png',
  actor: 'actor.png',
  driver: 'driver.png',
  mattress_tester : 'mattress tester.png',
  risk_analyst: 'risk analyst.png',
  astronaut: 'astronaut.png',
  employee: 'employee.png',
  medician: 'medician.png',
  santa_claus : 'santa claus.png',
  barber: 'barber.png',
  entrepreneur: 'entrepreneur.png',
  nurse: 'nurse.png',
  santa: 'santa.png',
  barman: 'barman.png',
  fireman: 'fireman.png',
  painter: 'painter.png',
  soldier: 'soldier.png',
  beach_guard: 'beach guard.png',
  fitness_influencer: 'fitness influencer.png',
  pet_sitter: 'pet sitter.png',
  soldier: 'soldier.png',
  beer_delivery: 'beer delivery.png',
  freelancer: 'freelancer.png',
  photographer: 'photographer.png',
  swimming_instructor : 'swimming instructor.png',
  bodybuilder: 'bodybuilder.png',
  gamer: 'gamer.png',
  physiotherapist: 'physiotherapist.png',
  teacher: 'teacher.png',
  bodyguard: 'bodyguard.png',
  general_practitioner: 'general practitioner.png',
  plumber: 'plumber.png',
  traniner: 'traniner.png',
  business_man: 'business man.png',
  guru: 'guru.png',
  police_agent : 'police agent.png',
  travel_influencer : 'travel influencer.png',
  business_traveler : 'business traveler.png',
  gym_bro: 'gym bro.png',
  policeman: 'policeman.png',
  traveller: 'traveller.png',
  car_washer: 'car washer.png',
  gynecologist: 'gynecologist.png',
  priest: 'priest.png',
  tutor: 'tutor.png',
  ceo: 'ceo.png',
  heir: 'heir.png',
  primary_care_doctor: 'primary care doctor.png',
  unemployed: 'unemployed.png',
  consultant: 'consultant.png',
  househusband: 'househusband.png',
  prison_officer : 'prison officer.png',
  waiter: 'waiter.png',
  default: 'default.png',
  lawyer: 'lawyer.png',
  professor: 'professor.png',
  wedding_planner : 'wedding planner.png',
  digital_nomads : 'digital nomads.png',
  manager: 'manager.png',
  ranger: 'ranger.png',
  youtuber: 'youtuber.png',
};

export default imageMap;
